vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles' #chemin de l'instalation 
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer #Permet d'éviter un conflit avec les images si elles ont le meme nom
           delete_on_remove: true #Permet en cas de supression d'image, de la suprimer du stock
           delete_on_update: true #Permet en cas de modification d'image, de la suprimer du stock
           inject_on_load: false #Permet en cas d'echec de chargement lors d'un fremplissage de formulaire de ne pas l'uploader 
       
        users:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users' #chemin de l'instalation 
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer #Permet d'éviter un conflit avec les images si elles ont le meme nom
           delete_on_remove: true #Permet en cas de supression d'image, de la suprimer du stock
           delete_on_update: true #Permet en cas de modification d'image, de la suprimer du stock
           inject_on_load: false #Permet en cas d'echec de chargement lors d'un fremplissage de formulaire de ne pas l'uploader 
           


